dtb-$(CONFIG_ARCH_SUN55IW3) += \
	sun55iw3p1-pwm0-7.dtbo \
	sun55iw3p1-spi1-enc28j60.dtbo \
	sun55iw3p1-spi1-spidev.dtbo \
	sun55iw3p1-spi2-spidev.dtbo \
	sun55iw3p1-twi1.dtbo \
	sun55iw3p1-twi2.dtbo \
	sun55iw3p1-twi4.dtbo \
	sun55iw3p1-twi5.dtbo \
	sun55iw3p1-uart3.dtbo \
	sun55iw3p1-uart4.dtbo \
	sun55iw3p1-uart5.dtbo \
	sun55iw3p1-uart6.dtbo \
	sun55iw3p1-uart7.dtbo \
	sun55iw3p1-usbc0-peripheral.dtbo \
	sun55iw3p1-usbc0-host.dtbo \
	cubie-a5e-enable-usb3.dtbo \
	cubie-a5e-radxa-camera-8m-219.dtbo \
	cubie-a5e-radxa-display-8hd.dtbo \
	cubie-a5e-radxa-display-10fhd.dtbo 

dtb-$(CONFIG_ARCH_SUN60IW2) += \
	sun60iw2p1-i2s0-2ch.dtbo \
	sun60iw2p1-i2s4-2ch.dtbo \
	sun60iw2p1-pwm1-2.dtbo \
	sun60iw2p1-spi1-spidev.dtbo \
	sun60iw2p1-spi3-spidev.dtbo \
	sun60iw2p1-twi7.dtbo \
	sun60iw2p1-uart4.dtbo \
	cubie-a7a-radxa-25w-poe.dtbo \
	cubie-a7a-radxa-camera-8m-219.dtbo \
	cubie-a7a-radxa-camera-13m-214.dtbo \
	cubie-a7a-radxa-camera-4k-415.dtbo \
	cubie-a7a-radxa-display-8hd.dtbo \
	cubie-a7a-radxa-display-10fhd.dtbo

targets += $(dtb-y)

always-y		:= $(dtb-y)
clean-files		:= *.dtbo *.scr
