dtb-$(CONFIG_ARCH_SUN55IW3) += \
	radxa-cubie-a5e-enbale-usb3.dtbo \
	sun55iw3p1-pwm0-7.dtbo \
	sun55iw3p1-spi1-enc28j60.dtbo \
	sun55iw3p1-spi1-spidev.dtbo \
	sun55iw3p1-twi1.dtbo \
	sun55iw3p1-uart3.dtbo \
	sun55iw3p1-usbc0-peripheral.dtbo \
	sun55iw3p1-usbc0-host.dtbo 

targets += $(dtb-y)

always-y		:= $(dtb-y)
clean-files		:= *.dtbo *.scr
