subdir-y += arch/arm64/boot/dts/allwinner/overlays
subdir-y += arch/arm64/boot/dts/amlogic/overlays
subdir-y += arch/arm64/boot/dts/rockchip/overlays
subdir-y += arch/arm64/boot/dts/qcom/overlays
obj-m := radxa-overlays.o
