#ifndef _DRM_MIPI_DSI_H_OVERLAY_
#define _DRM_MIPI_DSI_H_OVERLAY_

#include <dt-bindings/display/drm_mipi_dsi.h>

#ifndef MIPI_DSI_MODE_VIDEO_HFP
#define MIPI_DSI_MODE_VIDEO_HFP MIPI_DSI_MODE_VIDEO_NO_HFP
#endif /* MIPI_DSI_MODE_VIDEO_HFP */

#ifndef MIPI_DSI_MODE_VIDEO_HBP
#define MIPI_DSI_MODE_VIDEO_HBP MIPI_DSI_MODE_VIDEO_NO_HBP
#endif /* MIPI_DSI_MODE_VIDEO_HBP */

#ifndef MIPI_DSI_MODE_VIDEO_HSA
#define MIPI_DSI_MODE_VIDEO_HSA MIPI_DSI_MODE_VIDEO_NO_HSA
#endif /* MIPI_DSI_MODE_VIDEO_HSA */

#ifndef MIPI_DSI_MODE_EOT_PACKET
#define MIPI_DSI_MODE_EOT_PACKET MIPI_DSI_MODE_NO_EOT_PACKET
#endif /* MIPI_DSI_MODE_EOT_PACKET */

#endif /* _DRM_MIPI_DSI_H_OVERLAY_ */
